### ISSUE TITLE
feat: add AWS secert manager support as a secret layer for holding CN configuration

### ISSUE THREAD

**Issue by moabu** [GluuFederation/pygluu-containerlib#35]
Similar to the google secert handler, an AWS secret handler should be added to support multi regional setups with [AWS secret manager](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/secretsmanager.html) has the holder of the secret and configuration output.

**Comment by iromli** [comment]
Feature implemented in https://github.com/GluuFederation/pygluu-containerlib/releases/tag/2.16.0
