### ISSUE TITLE
AWS Config/Secret Wrong function name

### ISSUE THREAD

**Issue by venc-gy** [GluuFederation/pygluu-containerlib#37]
https://github.com/GluuFederation/pygluu-containerlib/blob/8a3b2c1bd5767e006b8ea64c0e9a0f4ec769e808/pygluu/containerlib/config/aws_config.py#L127

Should this function name be  `def all(self)` instead? Same for aws_secret as well. Otherwise base_config and base_secret will raise NotImplementedError.

**Comment by venc-gy** [comment]
Instead of changing the function (due to internal references), added a new `all()` function

**Comment by iromli** [comment]
Fixed in latest branch `v2`.
